name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore ClassLibraryProjects/StringLibrary.sln
      
    - name: Build
      run: dotnet build ClassLibraryProjects/StringLibrary.sln --no-restore
      
    - name: Test
      run: dotnet test ClassLibraryProjects/StringLibrary.sln --no-build --verbosity normal
