name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      working-directory: ./ClassLibraryProjects
      run: dotnet restore
      
    - name: Build
      working-directory: ./ClassLibraryProjects
      run: dotnet build --no-restore
      
    - name: Test with coverage
      working-directory: ./ClassLibraryProjects
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./TestResults --logger "trx;LogFileName=test-results.trx"

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: ./ClassLibraryProjects/TestResults
        retention-days: 30
        
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: .NET Tests
        path: "**/TestResults/*.trx"
        reporter: dotnet-trx
        fail-on-error: true
